=== brbrown25/aaf/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPDerivationChain.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % MOB "top-level | lower-level | sub-clip | adjusted-clip | template-clip | clip | file-source | recording-source | import-source | tape-source | film-source | auxiliary-source">
<!ENTITY % MOB_SLOT "timeline-mob-slot | static-mob-slot | event-mob-slot">
<!ENTITY % OPERATION_GROUP "video-dissolve | smpte-video-wipe | video-speed-control | video-repeat | video-flip | video-flop | video-flip-flop | video-position | video-crop | video-scale | video-rotate | video-corner-pinning | alpha-with-video-key | separate-alpha-key | luminance-key | chroma-key | mono-audio-gain | mono-audio-pan | mono-audio-dissolve | two-parameter-mono-audio-dissolve">
<!ENTITY % SOURCE_REFERENCE "source-clip | eoc | oof">
<!ENTITY % SEGMENT "sequence | timecode | timecode-stream-12m | edgecode | comment-marker | descriptive-marker | %SOURCE_REFERENCE; | %OPERATION_GROUP;">
<!ENTITY % COMPONENT "transition | %SEGMENT;">
<!ENTITY % COMMENTS_AND_COMPONENTS "( comment | %COMPONENT; )*">
<!ENTITY % COMMENTS_AND_SEGMENTS "( comment | %SEGMENT; )*">
<!ENTITY % ESSENCE_TYPE "none | audio | picture | timecode | edgecode | auxiliary">

<!ELEMENT aaf-file ( %MOB; )+>

<!-- Mobs -->

<!ELEMENT top-level ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST top-level name CDATA #IMPLIED>

<!ELEMENT lower-level ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST lower-level name CDATA #IMPLIED>

<!ELEMENT sub-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST sub-clip name CDATA #IMPLIED>

<!ELEMENT adjusted-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST adjusted-clip name CDATA #IMPLIED>

<!ELEMENT template-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST template-clip name CDATA #IMPLIED>

<!ELEMENT clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST clip name CDATA #IMPLIED>

<!ELEMENT file-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST file-source 
	name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
>

<!ELEMENT recording-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST recording-source name CDATA #IMPLIED>

<!ELEMENT import-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST import-source name CDATA #IMPLIED>

<!ELEMENT tape-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST tape-source name CDATA #IMPLIED>

<!ELEMENT film-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST film-source name CDATA #IMPLIED>

<!ELEMENT auxiliary-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST auxiliary-source name CDATA #IMPLIED>

<!-- Comments -->
<!ELEMENT comment EMPTY>
<!ATTLIST comment
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!-- Type A Components -->

<!ELEMENT timecode ( comment* )>
<!ATTLIST timecode track-type ( timecode ) #REQUIRED>

<!ELEMENT edgecode ( comment* )>
<!ATTLIST edgecode track-type ( edgecode ) #REQUIRED>

<!ELEMENT timecode-stream-12m ( comment* )>
<!ATTLIST timecode-stream-12m track-type ( timecode ) #REQUIRED>

<!ELEMENT eoc ( comment* )>
<!ATTLIST eoc track-type ( %ESSENCE_TYPE; ) #REQUIRED>

<!ELEMENT oof ( comment* )>
<!ATTLIST oof track-type ( %ESSENCE_TYPE; ) #REQUIRED>

<!-- Type B Components -->

<!ELEMENT source-clip ( comment*, ( %MOB; ), comment* )>
<!ATTLIST source-clip track-type ( none | audio | picture | auxiliary ) #REQUIRED>

<!-- Type C Components -->
<!ELEMENT transition ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST transition track-type ( %ESSENCE_TYPE; ) #REQUIRED>

<!ELEMENT sequence ( comment*, ( %COMPONENT; ), %COMMENTS_AND_COMPONENTS; )>
<!ATTLIST sequence track-type ( %ESSENCE_TYPE; ) #REQUIRED>

<!ELEMENT comment-marker ( comment*, ( %SOURCE_REFERENCE; )?, comment* )>
<!ATTLIST comment-marker track-type ( %ESSENCE_TYPE; ) #REQUIRED>

<!ELEMENT descriptive-marker ( comment*, ( ( ( %SOURCE_REFERENCE; )?, comment*, descriptive-framework? ) | ( descriptive-framework?, comment*, ( %SOURCE_REFERENCE; )? ) ), comment* )>
<!ATTLIST descriptive-marker track-type ( %ESSENCE_TYPE; ) #REQUIRED>

<!-- Type D components -->

<!--
    Operation Groups:
    	In Specification:
    		Contain 1 SourceReference (pre-rendered version)
    		n Parameters
    		m Segments
    	In XML:
    		Contain 1 Segment
-->

<!ELEMENT video-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-dissolve track-type ( picture ) #REQUIRED>

<!ELEMENT smpte-video-wipe ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST smpte-video-wipe track-type ( picture ) #REQUIRED>

<!ELEMENT video-speed-control ( %COMMENTS_AND_COMPONENTS;, speed-ratio?, %COMMENTS_AND_COMPONENTS; )>
<!ATTLIST video-speed-control track-type ( picture ) #REQUIRED>

	<!ELEMENT speed-ratio EMPTY>
	<!ATTLIST speed-ratio
        numerator CDATA #REQUIRED
        denominator CDATA #REQUIRED
    >

<!ELEMENT video-repeat ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-repeat track-type ( picture ) #REQUIRED>

<!ELEMENT video-flip ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flip track-type ( picture ) #REQUIRED>

<!ELEMENT video-flop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flop track-type ( picture ) #REQUIRED>

<!ELEMENT video-flip-flop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flip-flop track-type ( picture ) #REQUIRED>

<!ELEMENT video-position ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-position track-type ( picture ) #REQUIRED>

<!ELEMENT video-crop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-crop track-type ( picture ) #REQUIRED>

<!ELEMENT video-scale ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-scale track-type ( picture ) #REQUIRED>

<!ELEMENT video-rotate ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-rotate track-type ( picture ) #REQUIRED>

<!ELEMENT video-corner-pinning ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-corner-pinning track-type ( picture ) #REQUIRED>

<!ELEMENT alpha-with-video-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST alpha-with-video-key track-type ( picture ) #REQUIRED>

<!ELEMENT separate-alpha-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST separate-alpha-key track-type ( picture ) #REQUIRED>

<!ELEMENT luminance-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST luminance-key track-type ( picture ) #REQUIRED>

<!ELEMENT chroma-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST chroma-key track-type ( picture ) #REQUIRED>

<!ELEMENT mono-audio-gain ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-gain track-type ( audio ) #REQUIRED>

<!ELEMENT mono-audio-pan ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-pan track-type ( audio ) #REQUIRED>

<!ELEMENT mono-audio-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-dissolve track-type ( audio ) #REQUIRED>

<!ELEMENT two-parameter-mono-audio-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST two-parameter-mono-audio-dissolve track-type ( audio ) #REQUIRED>

<!-- Mob Slots -->

<!ELEMENT timeline-mob-slot ( %SEGMENT; )>
<!ATTLIST timeline-mob-slot
    edit-rate-numerator CDATA #REQUIRED
    edit-rate-denominator CDATA #REQUIRED
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
>

<!ELEMENT static-mob-slot ( %SEGMENT; )>
<!ATTLIST static-mob-slot
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
>

<!ELEMENT event-mob-slot ( %SEGMENT; )>
<!ATTLIST event-mob-slot
    edit-rate-numerator CDATA #REQUIRED
    edit-rate-denominator CDATA #REQUIRED
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
>

<!-- Other Interchange Objects -->
<!ELEMENT descriptive-framework EMPTY>

<!-- End a derivation chain on a mob -->
<!ELEMENT bad-eoc EMPTY>

=== brbrown25/aaf/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPAnnotationTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">

<aaf-file>

    <!-- Test UserComments property -->
    <top-level name="User Comments in Mob Slot Segment">
        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
            <source-clip track-type="none">
                <comment value="Should Pass" name="Test Case 1"/>
                <lower-level>
                    <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
                        <eoc track-type="none"/>
                    </timeline-mob-slot>
                </lower-level>
            </source-clip>
        </timeline-mob-slot>
    </top-level>
    
    <top-level name="User Comments in CommentMarker">
		<event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
            <sequence track-type="none">
				<comment-marker track-type="none">
                    <comment value="Should Pass" name="Test Case 2"/>
                </comment-marker>
            </sequence>
        </event-mob-slot>
    </top-level>
    
    <top-level name="Illegal User Comments">
        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
			<sequence track-type="none">
                <sequence track-type="none">
                    <comment value="Should Fail" name="Test Case 3"/>
                    <eoc track-type="none"/>
                </sequence>
            </sequence>
        </timeline-mob-slot>
    </top-level>

	<!-- Test CommentMarkes in essence/non-essence tracks -->
    <!-- Note: Case 2 above tests CommentMarkers in non-essence tracks -->
    <top-level name="CommentMarker in Essence Track">
		<event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
            <sequence track-type="audio">
				<comment-marker track-type="audio"/>
            </sequence>
        </event-mob-slot>
    </top-level>
    
    <top-level name="DescriptiveMarker in Essence Track">
		<event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
            <sequence track-type="audio">
				<descriptive-marker track-type="audio"/>
            </sequence>
        </event-mob-slot>
    </top-level>

	<!-- NEED TO TEST A DESCRIPTIVE MARKER IN AN ESSENCE TRACK -->
    
    <!-- Test CommentMarkes in Mob Slots (and nested in mob slots) -->
    <!-- Note: "CommentMarker in Essence Track" above test tests nested in an event mob slot -->
    <top-level name="CommentMarker in Event Mob Slot">
		<event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
			<comment-marker track-type="none"/>
        </event-mob-slot>
    </top-level>
    
    <top-level name="CommentMarker nested in Timeline Mob Slot">
		<timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
            <sequence track-type="none">
				<comment-marker track-type="none"/>
            </sequence>
        </timeline-mob-slot>
    </top-level>
    
    <top-level name="CommentMarker in Timeline Mob Slot">
		<timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
			<comment-marker track-type="none"/>
        </timeline-mob-slot>
    </top-level>
    
	<top-level name="CommentMarker nested in Static Mob Slot">
		<static-mob-slot>
            <sequence track-type="none">
				<comment-marker track-type="none"/>
            </sequence>
        </static-mob-slot>
    </top-level>
    
    <top-level name="CommentMarker in Static Mob Slot">
		<static-mob-slot>
			<comment-marker track-type="none"/>
        </static-mob-slot>
    </top-level>
    
    <!-- Note: "DescriptiveMarker in Essence Track" above test tests nested in an event mob slot -->
    <top-level name="DescriptiveMarker in Event Mob Slot">
		<event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
			<descriptive-marker track-type="none"/>
        </event-mob-slot>
    </top-level>
    
    <top-level name="DescriptiveMarker nested in Timeline Mob Slot">
		<timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
            <sequence track-type="none">
				<descriptive-marker track-type="none"/>
            </sequence>
        </timeline-mob-slot>
    </top-level>
    
    <top-level name="DescriptiveMarker in Timeline Mob Slot">
		<timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
			<descriptive-marker track-type="none"/>
        </timeline-mob-slot>
    </top-level>
    
	<top-level name="DescriptiveMarker nested in Static Mob Slot">
		<static-mob-slot>
            <sequence track-type="none">
				<descriptive-marker track-type="none"/>
            </sequence>
        </static-mob-slot>
    </top-level>
    
    <top-level name="DescriptiveMarker in Static Mob Slot">
		<static-mob-slot>
			<descriptive-marker track-type="none"/>
        </static-mob-slot>
    </top-level>

</aaf-file>

=== brbrown25/aaf/Utilities/AAFAnalyzer/RegressionTest/TestStructure/GraphBuilder-ResolveRefTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "../TestFiles/EPDerivationChain.dtd">

<aaf-file>
	
    <!--
         Set up a file that can be used to test that:
        
         (1) The TestGraph is build properly.
         (2) References are correctly resolved.
        
         The regression test code assumes the structure of this file, therefore
         any modifications to this file should be accompinied by modifications
         to the regression test.
    -->

    <!--
		 NOTE: The structure of these 5 mobs are identical with the following
        	   exceptions.
        	(1) Mob 1 referes to Mob 2, Mob 3, Mob 4 and Mob 5 while the other
        		mobs have end of chain references.
        	(2) Mob 1, Mob 4 and Mob 5 have their first slot contain a sequence
        		of 3 source clips and their second slot contain a single source
        		clip.  Mob 2 and Mob 3 have the order of slots refersed.
    -->
    
    <top-level name="Mob 1">
        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 1.A">
            <sequence track-type="audio">
                <source-clip track-type="audio" length="1">
                                    
                    <clip name="Mob 2">
                        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 2.B">
							<eoc track-type="audio" length="1"/>
                        </timeline-mob-slot>
                        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 2.A">
                            <sequence track-type="audio">
								<eoc track-type="audio" length="1"/>
                                <eoc track-type="audio" length="1"/>
                                <eoc track-type="audio" length="1"/>
                            </sequence>
                        </timeline-mob-slot>
                    </clip>
                    
                </source-clip>
				<source-clip track-type="audio" length="1">
                    
                    <clip name="Mob 3">
						<timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 3.B">
							<eoc track-type="audio" length="1"/>
                        </timeline-mob-slot>
                        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 3.A">
                            <sequence track-type="audio">
								<eoc track-type="audio" length="1"/>
                                <eoc track-type="audio" length="1"/>
                                <eoc track-type="audio" length="1"/>
                            </sequence>
                        </timeline-mob-slot>
                    </clip>
                    
                </source-clip>
				<source-clip track-type="audio" length="1">
                    
                    <clip name="Mob 4">
                        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 4.A">
                            <sequence track-type="audio">
								<eoc track-type="audio" length="1"/>
                                <eoc track-type="audio" length="1"/>
                                <eoc track-type="audio" length="1"/>
                            </sequence>
                        </timeline-mob-slot>
                        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 4.B">
							<eoc track-type="audio" length="1"/>
                        </timeline-mob-slot>
                    </clip>
                    
                </source-clip>
            </sequence>
        </timeline-mob-slot>
        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 1.B">
            <source-clip track-type="audio" length="1">
                
                    <clip name="Mob 5">
                        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 5.A">
                            <sequence track-type="audio">
								<eoc track-type="audio" length="1"/>
                                <eoc track-type="audio" length="1"/>
                                <eoc track-type="audio" length="1"/>
                            </sequence>
                        </timeline-mob-slot>
                        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1" name="Slot 5.B">
							<eoc track-type="audio" length="1"/>
                        </timeline-mob-slot>
                    </clip>
                
            </source-clip>
        </timeline-mob-slot>
    </top-level>
        
</aaf-file>

=== brbrown25/aaf/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPEditRateTest5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">

<aaf-file>

    <!-- Test all static tracks -->

    <clip name="Clip 1">
        <source-clip slot-type="static" edit-rate-denominator="1" edit-rate-numerator="1" track-type="audio">
            <file-source name="File Source 1" sample-rate-denominator="24" sample-rate-numerator="600">
                <eoc/>
            </file-source>
        </source-clip>
    </clip>
    <clip name="Clip 2">
        <source-clip slot-type="static" edit-rate-denominator="1" edit-rate-numerator="1" track-type="audio">
            <file-source name="File Source 1" sample-rate-denominator="24" sample-rate-numerator="1200000">
                <eoc/>
            </file-source>
        </source-clip>
    </clip>

</aaf-file>

=== brbrown25/aaf/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPNameTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">

<aaf-file>

    <!-- Test named/unamed mobs -->

    <top-level name="Named Top-Level"><eoc/></top-level>
	<top-level><eoc/></top-level>
    
    <lower-level name = "Named Lower-Level"><eoc/></lower-level>
    <lower-level><eoc/></lower-level>
    
    <sub-clip name = "Named Sub-Clip"><eoc/></sub-clip>
    <sub-clip><eoc/></sub-clip>
    
    <adjusted-clip name = "Named Adjusted Clip"><eoc/></adjusted-clip>
    <adjusted-clip><eoc/></adjusted-clip>
    
    <template-clip name = "Named Template Clip"><eoc/></template-clip>
    <template-clip><eoc/></template-clip>
    
    <clip name = "Named Clip"><eoc/></clip>
    <clip><eoc/></clip>
    
    <file-source name = "Named File Source"><eoc/></file-source>
    <file-source><eoc/></file-source>
    
    <recording-source name = "Named Recording Source"><eoc/></recording-source>
    <recording-source><eoc/></recording-source>
    
    <import-source name = "Named Import Source"><eoc/></import-source>
    <import-source><eoc/></import-source>
    
    <tape-source name = "Named Tape Source"><eoc/></tape-source>
    <tape-source><eoc/></tape-source>
    
    <film-source name = "Named Film Source"><eoc/></film-source>
    <film-source><eoc/></film-source>
    
    <!-- Test non-unique Top-Level/Lower Level -->

    <top-level name = "Duplicate: Top-Level/Lower-Level"><eoc/></top-level>
    <lower-level name = "Duplicate: Top-Level/Lower-Level"><eoc/></lower-level>
    
	<!-- Test non-unique Top-Level -->

    <top-level name = "Duplicate: Top-Level"><eoc/></top-level>        
    <top-level name = "Duplicate: Top-Level"><eoc/></top-level>
    	
    <top-level name = "Duplicate: Top-Level/Sub-Clip"><eoc/></top-level>        
    <sub-clip name = "Duplicate: Top-Level/Sub-Clip"><eoc/></sub-clip>

    <top-level name = "Duplicate: Top-Level/Adjusted Clip"><eoc/></top-level>
    <adjusted-clip name = "Duplicate: Top-Level/Adjusted Clip"><eoc/></adjusted-clip>
    
	<top-level name = "Duplicate: Top-Level/Template Clip"><eoc/></top-level>
    <template-clip name = "Duplicate: Top-Level/Template Clip"><eoc/></template-clip>
    
    <top-level name = "Duplicate: Top-Level/Clip"><eoc/></top-level>
    <clip name = "Duplicate: Top-Level/Clip"><eoc/></clip>
    
    <top-level name = "Duplicate: Top-Level/File Source"><eoc/></top-level>
    <file-source name = "Duplicate: Top-Level/File Source"><eoc/></file-source>
    
    <top-level name = "Duplicate: Top-Level/Recording Source"><eoc/></top-level>
    <recording-source name = "Duplicate: Top-Level/Recording Source"><eoc/></recording-source>
    
    <top-level name = "Duplicate: Top-Level/Import Source"><eoc/></top-level>
    <import-source name = "Duplicate: Top-Level/Import Source"><eoc/></import-source>
    
    <top-level name = "Duplicate: Top-Level/Tape Source"><eoc/></top-level>
    <tape-source name = "Duplicate: Top-Level/Tape Source"><eoc/></tape-source>
    
    <top-level name = "Duplicate: Top-Level/Film Source"><eoc/></top-level>
    <film-source name = "Duplicate: Top-Level/Film Source"><eoc/></film-source>
    
	<!-- Test non-unique Lower-Level -->

    <lower-level name = "Duplicate: Lower-Level"><eoc/></lower-level>        
    <lower-level name = "Duplicate: Lower-Level"><eoc/></lower-level>
    	
    <lower-level name = "Duplicate: Lower-Level/Sub-Clip"><eoc/></lower-level>        
    <sub-clip name = "Duplicate: Lower-Level/Sub-Clip"><eoc/></sub-clip>

    <lower-level name = "Duplicate: Lower-Level/Adjusted Clip"><eoc/></lower-level>
    <adjusted-clip name = "Duplicate: Lower-Level/Adjusted Clip"><eoc/></adjusted-clip>
    
	<lower-level name = "Duplicate: Lower-Level/Template Clip"><eoc/></lower-level>
    <template-clip name = "Duplicate: Lower-Level/Template Clip"><eoc/></template-clip>
    
    <lower-level name = "Duplicate: Lower-Level/Clip"><eoc/></lower-level>
    <clip name = "Duplicate: Lower-Level/Clip"><eoc/></clip>
    
    <lower-level name = "Duplicate: Lower-Level/File Source"><eoc/></lower-level>
    <file-source name = "Duplicate: Lower-Level/File Source"><eoc/></file-source>
    
    <lower-level name = "Duplicate: Lower-Level/Recording Source"><eoc/></lower-level>
    <recording-source name = "Duplicate: Lower-Level/Recording Source"><eoc/></recording-source>
    
    <lower-level name = "Duplicate: Lower-Level/Import Source"><eoc/></lower-level>
    <import-source name = "Duplicate: Lower-Level/Import Source"><eoc/></import-source>
    
    <lower-level name = "Duplicate: Lower-Level/Tape Source"><eoc/></lower-level>
    <tape-source name = "Duplicate: Lower-Level/Tape Source"><eoc/></tape-source>
    
    <lower-level name = "Duplicate: Lower-Level/Film Source"><eoc/></lower-level>
    <film-source name = "Duplicate: Lower-Level/Film Source"><eoc/></film-source>
    
</aaf-file>
